# chainlit.config.toml

[project]
name = "Gynecologist Assistant"

[features]
# Enable chat history
chat_history = true
# Enable file uploads
multi_modal = true

[ui]
name = "Gynecologist Assistant"
description = "Your personal AI powered by Gemini"
show_footer = true
footer_text = "Powered by ZZWICK Hygiene."

[ui.theme]
primary_color = "#4F46E5"

[ui.github]
show_github = false

# Enable file uploads
[ui.input]
disable_file_upload = false
